"""add holdings table

Revision ID: 0465c404b625
Revises: 92dbb8f66968
Create Date: 2025-10-18 01:50:31.084560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0465c404b625'
down_revision: Union[str, Sequence[str], None] = '92dbb8f66968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('holding_since', sa.DateTime(), nullable=False))
    op.drop_column('holdings', 'days_held')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('days_held', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('holdings', 'holding_since')
    # ### end Alembic commands ###
