"""add_investment_preference_table

Revision ID: 33860f4579bc
Revises: bbc3b725ff82
Create Date: 2025-11-02 20:16:47.733061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33860f4579bc'
down_revision: Union[str, Sequence[str], None] = 'bbc3b725ff82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('risk_tolerance', sa.Enum('CONSERVATIVE', 'MODERATE', 'AGGRESSIVE', name='risktolerance'), nullable=False),
    sa.Column('investment_horizon', sa.Enum('SHORT_TERM', 'MEDIUM_TERM', 'LONG_TERM', name='investmenthorizon'), nullable=False),
    sa.Column('target_annual_return', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='targetannualreturn'), nullable=False),
    sa.Column('monthly_investment_range', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', 'TIER_4', 'TIER_5', 'TIER_6', name='monthlyinvestmentrange'), nullable=False),
    sa.Column('preferred_sectors', sa.ARRAY(sa.Enum('TECHNOLOGY', 'HEALTHCARE', 'FINANCIAL_SERVICES', 'CONSUMER_DISCRETIONARY', 'CONSUMER_STAPLES', 'INDUSTRIALS', 'ENERGY', 'MATERIALS', 'REAL_ESTATE', 'UTILITIES', 'TELECOMMUNICATIONS', 'AUTOMOTIVE', 'AEROSPACE_DEFENSE', 'BIOTECHNOLOGY', 'RENEWABLE_ENERGY', 'E_COMMERCE', 'ARTIFICIAL_INTELLIGENCE', 'CRYPTOCURRENCY', 'CLOUD_COMPUTING', 'CYBERSECURITY', name='sectors')), server_default='{}', nullable=True),
    sa.Column('avoid_sectors', sa.ARRAY(sa.Enum('TECHNOLOGY', 'HEALTHCARE', 'FINANCIAL_SERVICES', 'CONSUMER_DISCRETIONARY', 'CONSUMER_STAPLES', 'INDUSTRIALS', 'ENERGY', 'MATERIALS', 'REAL_ESTATE', 'UTILITIES', 'TELECOMMUNICATIONS', 'AUTOMOTIVE', 'AEROSPACE_DEFENSE', 'BIOTECHNOLOGY', 'RENEWABLE_ENERGY', 'E_COMMERCE', 'ARTIFICIAL_INTELLIGENCE', 'CRYPTOCURRENCY', 'CLOUD_COMPUTING', 'CYBERSECURITY', name='sectors')), server_default='{}', nullable=True),
    sa.Column('max_position_size', sa.Float(), nullable=True),
    sa.Column('dividend_focus', sa.Boolean(), nullable=True),
    sa.Column('esg_focus', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_investment_preference_id'), 'investment_preference', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_preference_id'), table_name='investment_preference')
    op.drop_table('investment_preference')
    # ### end Alembic commands ###
