"""add isin number

Revision ID: 5b45c2b1c51d
Revises: dee6b9cbd61a
Create Date: 2025-11-20 23:48:10.787400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b45c2b1c51d'
down_revision: Union[str, Sequence[str], None] = 'dee6b9cbd61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('isin_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'isin_number')
    # ### end Alembic commands ###
