"""add holdings table

Revision ID: 92dbb8f66968
Revises: 50f35b427389
Create Date: 2025-10-18 01:35:42.054946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92dbb8f66968'
down_revision: Union[str, Sequence[str], None] = '50f35b427389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('days_held', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'days_held')
    # ### end Alembic commands ###
